# Generated by Django 6.1.1 on 2026-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=16)),
                ('scope', models.CharField(blank=True, default='', max_length=32)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prefix', 'scope', 'year'), name='uniq_code_sequence')],
            },
        ),
    ]
