# Generated by Django 6.1.1 on 2026-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-occurred_at'], 'permissions': [('view_audit_logs', 'Can view audit logs')]},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
