# Generated by Django 6.1.1 on 2026-10-03 11:24

import apps.employees.models.reference
import apps.employees.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=80, verbose_name='last name')),
                ('preferred_name', models.CharField(blank=True, help_text='What the person is actually called. Shown instead of the full name when set.', max_length=80, verbose_name='preferred name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Optional. Age is always calculated, never stored.', null=True, validators=[apps.employees.validators.validate_date_of_birth], verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Not declared is a valid answer.', max_length=20)),
                ('nationality', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code from the configured country list.', max_length=2, validators=[apps.employees.models.reference.validate_nationality])),
                ('profile_photo', models.ImageField(blank=True, help_text='Optional. JPEG, PNG, GIF or WEBP.', upload_to='employees/photos/%Y/%m/', validators=[apps.employees.validators.validate_profile_photo], verbose_name='profile photo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_person',
                'ordering': ['last_name', 'first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('employee_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', help_text='Master-record state only; employment lifecycle is a later phase.', max_length=10)),
                ('archived_at', models.DateTimeField(blank=True, help_text='Set when the record was archived.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Optional login account. Never created automatically; linking is audited.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(help_text='The human being. One employee record per person; re-hire creates an Employment.', on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='employees.person')),
            ],
            options={
                'db_table': 'employees_employee',
                'ordering': ['code'],
                'permissions': [('view_sensitive_identity', 'Can view sensitive identity data (identifiers, photo)'), ('view_identifiers', 'Can view employee identifiers'), ('view_sensitive_contacts', 'Can view personal contact details and addresses'), ('view_emergency_contacts', 'Can view emergency contacts'), ('manage_contacts', 'Can add and change employee contacts'), ('manage_addresses', 'Can add and change employee addresses'), ('manage_emergency_contacts', 'Can add and change emergency contacts'), ('manage_identifiers', 'Can add and change employee identifiers'), ('manage_relationships', 'Can add and change person relationships'), ('manage_notes', 'Can add and remove internal employee notes'), ('link_user', 'Can link or unlink a user account to an employee'), ('view_employee_timeline', 'Can view the employee timeline'), ('archive_employee', 'Can archive and reactivate employees'), ('export_employee', 'Can export employee data')],
            },
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('spouse', 'Spouse'), ('partner', 'Partner'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_from', to='employees.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_to', to='employees.person')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_person_relationship',
                'ordering': ['from_person__last_name', 'to_person__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('employee_created', 'Employee created'), ('employee_updated', 'Employee record updated'), ('employee_status_changed', 'Status changed'), ('employee_archived', 'Employee archived'), ('employee_reactivated', 'Employee reactivated'), ('person_updated', 'Personal details updated'), ('photo_removed', 'Profile photo removed'), ('identifier_added', 'Identifier added'), ('identifier_updated', 'Identifier updated'), ('identifier_verification_changed', 'Identifier verification changed'), ('identifier_viewed', 'Sensitive identifier viewed'), ('contact_added', 'Contact added'), ('contact_updated', 'Contact updated'), ('contact_removed', 'Contact removed'), ('address_added', 'Address added'), ('address_changed', 'Address changed'), ('address_ended', 'Previous address closed'), ('emergency_contact_added', 'Emergency contact added'), ('emergency_contact_updated', 'Emergency contact updated'), ('emergency_contact_removed', 'Emergency contact removed'), ('relationship_added', 'Relationship added'), ('relationship_removed', 'Relationship removed'), ('note_added', 'Note added'), ('note_removed', 'Note removed'), ('user_linked', 'User account linked'), ('user_unlinked', 'User account unlinked')], max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Require employees.view_sensitive_identity to see this entry.')),
                ('source_app', models.CharField(default='employees', help_text='Domain that produced the entry (later phases use their own label).', max_length=40)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='employees.employee')),
            ],
            options={
                'db_table': 'employees_timeline',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('partner', 'Partner'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('other', 'Other')], help_text='How this person is related to the employee.', max_length=20)),
                ('phone', models.CharField(max_length=40)),
                ('alternative_phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'db_table': 'employees_emergency_contact',
                'ordering': ['-is_primary', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='uniq_employee_primary_emergency_contact'), models.CheckConstraint(condition=models.Q(('relationship__in', ['spouse', 'partner', 'parent', 'child', 'sibling', 'guardian', 'other'])), name='employees_emergency_relationship_valid')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('mobile', 'Mobile'), ('phone', 'Phone (landline)'), ('email', 'Email'), ('alternative_email', 'Alternative email')], max_length=20)),
                ('value', models.CharField(max_length=160)),
                ('normalized_value', models.CharField(editable=False, max_length=160)),
                ('label', models.CharField(blank=True, help_text="Optional, e.g. 'work mobile' or 'personal email'.", max_length=60)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Set once the owner has confirmed they can be reached on it.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='employees.employee')),
            ],
            options={
                'db_table': 'employees_contact',
                'ordering': ['-is_primary', 'contact_type', 'created_at'],
                'indexes': [models.Index(fields=['contact_type', 'normalized_value'], name='emp_contact_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee', 'contact_type'), name='uniq_employee_primary_contact_type'), models.CheckConstraint(condition=models.Q(('contact_type__in', ['mobile', 'phone', 'email', 'alternative_email'])), name='employees_contact_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('current', 'Current address'), ('permanent', 'Permanent address'), ('other', 'Other address')], max_length=12)),
                ('address_line_1', models.CharField(max_length=200, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=200, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='state / province')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2, validators=[apps.employees.validators.validate_issuing_country])),
                ('is_primary', models.BooleanField(default=False, help_text='The current address of its type.')),
                ('effective_from', models.DateField(blank=True, help_text='Defaults to today when the address is recorded.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Last day this address applied (inclusive). Empty means current.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='employees.employee')),
            ],
            options={
                'db_table': 'employees_address',
                'ordering': ['-is_primary', '-effective_from', 'created_at'],
                'indexes': [models.Index(fields=['address_type', 'is_primary'], name='emp_address_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee', 'address_type'), name='uniq_employee_primary_address_type'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='employees_address_eff_dates'), models.CheckConstraint(condition=models.Q(('address_type__in', ['current', 'permanent', 'other'])), name='employees_address_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('cnic', 'CNIC (national identity card)'), ('passport', 'Passport'), ('national_id', 'National ID'), ('driving_licence', 'Driving licence'), ('nicop', 'NICOP / NCCOP'), ('other', 'Other official identifier')], max_length=20)),
                ('value', models.CharField(help_text='As issued. Stored unmasked, but always displayed masked without permission.', max_length=64)),
                ('normalized_value', models.CharField(editable=False, help_text='Upper-case, separator-free.', max_length=64)),
                ('issuing_country', models.CharField(blank=True, max_length=2, validators=[apps.employees.validators.validate_issuing_country])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='unverified', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='The identifier normally used to look this employee up.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_identifier',
                'ordering': ['-is_primary', 'identifier_type', 'created_at'],
                'indexes': [models.Index(fields=['identifier_type', 'issuing_country', 'normalized_value'], name='emp_ident_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee', 'identifier_type'), name='uniq_employee_primary_identifier_type'), models.UniqueConstraint(condition=models.Q(('verification_status', 'rejected'), _negated=True), fields=('identifier_type', 'issuing_country', 'normalized_value'), name='uniq_identifier_value_per_country'), models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('issue_date__isnull', True), ('expiry_date__gte', models.F('issue_date')), _connector='OR'), name='employees_identifier_eff_dates'), models.CheckConstraint(condition=models.Q(('verification_status__in', ['unverified', 'verified', 'rejected', 'expired'])), name='employees_identifier_verification_valid')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal (visible to HR)'), ('restricted', 'Restricted (sensitive-identity permission required)')], default='internal', max_length=12)),
                ('pinned', models.BooleanField(default=False, help_text='Keep at the top of the notes list.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_employee_note',
                'ordering': ['-pinned', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'visibility'], name='emp_note_emp_vis_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('visibility__in', ['internal', 'restricted'])), name='employees_note_visibility_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='emp_person_name_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender'], name='emp_person_gender_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['', 'male', 'female', 'other', 'prefer_not_to_say'])), name='employees_person_gender_valid'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('nationality', ''), ('nationality__regex', '^[A-Z]{2}$'), _connector='OR'), name='employees_person_nationality_code'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_status', 'created_at'], name='emp_emp_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employee_status__in', ['active', 'inactive', 'archived'])), name='employees_employee_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employee_status', 'archived'), ('archived_at__isnull', True), _connector='OR'), name='employees_employee_archived_flag'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.UniqueConstraint(fields=('from_person', 'to_person', 'relationship_type'), name='uniq_person_relationship'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_person', models.F('to_person')), _negated=True), name='employees_relationship_not_self'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('relationship_type__in', ['spouse', 'partner', 'parent', 'child', 'sibling', 'guardian', 'other'])), name='employees_relationship_type_valid'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['employee', '-occurred_at'], name='emp_timeline_time_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['employee', 'event_type'], name='emp_timeline_type_idx'),
        ),
    ]
