"""``EmployeeService`` - the heart of the employee master record (docs/adr/ADR-019/020/022).

Responsibilities, all of them Phase 3 and none of them later phases:

* create an employee (person + employee + generated code) atomically;
* change the **master-record** status only (active / inactive / archived);
* link or unlink an optional ``User`` account;
* keep the immutable ``code`` stable for the life of the record.

Explicitly *not* here: employment contracts, positions, organizational placement, manager, salary,
attendance or leave. Those are Phase 4+ and reference ``Employee`` from outside
(docs/adr/ADR-020).

Employee code (ADR-019): generated by ``apps.common.services.generate_code("EMP")`` which takes a
row lock on a counter, so two concurrent creations can never collide, and the value is checked for
collision before insert. ``count() + 1`` is never used.
"""

from __future__ import annotations

from typing import Any

from django.db import IntegrityError, transaction
from django.utils import timezone

from apps.common.exceptions import (
    BusinessRuleException,
    ConflictException,
    ValidationException,
)
from apps.common.request_context import SYSTEM_CONTEXT, RequestContext
from apps.common.services import generate_code, transactional
from apps.outbox.services import enqueue_outbox_event

from .. import events, permissions
from ..models import Employee, EmployeeStatus, Person
from .base import (
    EMPLOYEE,
    actor_or_none,
    audit,
    authorize,
    snapshot,
)
from .duplicate_service import DuplicateReport, DuplicateService
from .person_service import PersonService
from .timeline_service import record_event

CODE_PREFIX = "EMP"
CODE_WIDTH = 6

#: How many times a generated code is retried if it somehow collides. With a locked counter this
#: should never happen; the loop exists so a partial manual restore cannot break creation.
CODE_ATTEMPTS = 5


class EmployeeService:
    # --------------------------------------------------------------------------------- create
    @classmethod
    @transactional
    def create_employee(
        cls,
        *,
        actor: Any = None,
        person_data: dict[str, Any] | None = None,
        person: Any = None,
        status: str = EmployeeStatus.ACTIVE,
        link_user: Any = None,
        identifiers: list[dict[str, Any]] | None = None,
        contacts: list[dict[str, Any]] | None = None,
        addresses: list[dict[str, Any]] | None = None,
        emergency_contacts: list[dict[str, Any]] | None = None,
        profile_photo: Any = None,
        ctx: RequestContext = SYSTEM_CONTEXT,
    ) -> Employee:
        """Create an employee and everything that hangs off them, in one transaction.

        Either pass ``person_data`` (a new person is created) **or** ``person`` (an existing person
        is reused - the path recruitment will use so identity is never duplicated).

        Related records are optional. When several items of the same type are supplied, the first is
        made primary so the employee is immediately contactable.
        """
        authorize(actor, permissions.ADD)
        if person is None and not person_data:
            raise ValidationException(
                "Personal information is required.",
                details={"first_name": ["This field is required."]},
            )
        if person is None:
            person = PersonService.create_person(
                actor=actor, data=person_data or {}, profile_photo=profile_photo, ctx=ctx
            )
        elif getattr(person, "employee", None) is not None:
            raise ConflictException(
                "This person already has an employee record.", code="person_already_employed"
            )

        status = status or EmployeeStatus.ACTIVE
        if status not in EmployeeStatus.values:
            raise ValidationException(f"'{status}' is not a valid employee status.")

        employee = cls._insert(person=person, status=status, actor=actor)
        if link_user is not None:
            cls._link_user(employee, actor=actor, user=link_user, ctx=ctx)
        cls._create_related(
            employee,
            actor=actor,
            identifiers=identifiers,
            contacts=contacts,
            addresses=addresses,
            emergency_contacts=emergency_contacts,
            ctx=ctx,
        )
        audit(
            action="employee_created",
            actor=actor,
            obj_type=EMPLOYEE,
            obj_id=employee.pk,
            after=snapshot(employee, ("code", "employee_status")),
            person_id=str(person.pk),
            ctx=ctx,
        )
        record_event(
            employee=employee,
            event_type="employee_created",
            summary="Employee created",
            actor=actor,
            payload={"code": employee.code, "employee_status": employee.employee_status},
        )
        enqueue_outbox_event(
            events.EmployeeCreated(
                employee_id=str(employee.pk),
                employee_code=employee.code,
                actor_id=_actor_id(actor),
            ),
            aggregate_type=EMPLOYEE,
            aggregate_id=str(employee.pk),
        )
        return employee

    @classmethod
    def _insert(cls, *, person: Person, status: str, actor: Any) -> Employee:
        """Generate a unique code, then insert. ``PROTECT`` on person keeps history safe."""
        for _ in range(CODE_ATTEMPTS):
            employee = Employee(
                person=person,
                employee_status=status,
                code=generate_code(CODE_PREFIX, width=CODE_WIDTH),  # EMP-000001
                created_by=actor_or_none(actor),
                updated_by=actor_or_none(actor),
            )
            try:
                with transaction.atomic():
                    employee.save()
            except IntegrityError as exc:
                if "code" in str(exc).lower() or "unique" in str(exc).lower():
                    continue  # code collision: take the next number
                raise
            return employee
        raise ConflictException(
            "Could not allocate a unique employee code. Please try again.",
            code="code_allocation_failed",
        )

    @classmethod
    def _create_related(
        cls,
        employee: Employee,
        *,
        actor: Any,
        identifiers: list[dict[str, Any]] | None,
        contacts: list[dict[str, Any]] | None,
        addresses: list[dict[str, Any]] | None,
        emergency_contacts: list[dict[str, Any]] | None,
        ctx: RequestContext,
    ) -> None:
        """Create the optional child records through their own services (one rule set each)."""
        from .address_service import AddressService
        from .contact_service import ContactService
        from .emergency_contact_service import EmergencyContactService
        from .identifier_service import IdentifierService

        # "Primary" is per type: the first identifier/contact *of each type* becomes primary.
        seen: set[str] = set()
        for data in identifiers or []:
            payload = dict(data)
            payload.setdefault("is_primary", payload.get("identifier_type") not in seen)
            seen.add(payload.get("identifier_type", ""))
            IdentifierService.add_identifier(employee=employee, actor=actor, data=payload, ctx=ctx)
        seen = set()
        for data in contacts or []:
            payload = dict(data)
            payload.setdefault("is_primary", payload.get("contact_type") not in seen)
            seen.add(payload.get("contact_type", ""))
            ContactService.add_contact(employee=employee, actor=actor, data=payload, ctx=ctx)
        for data in addresses or []:
            AddressService.add_address(employee=employee, actor=actor, data=dict(data), ctx=ctx)
        for index, data in enumerate(emergency_contacts or []):
            payload = dict(data)
            payload.setdefault("is_primary", index == 0)
            EmergencyContactService.add_emergency_contact(
                employee=employee, actor=actor, data=payload, ctx=ctx
            )

    # --------------------------------------------------------------------------------- update
    @classmethod
    def check_duplicates(
        cls,
        *,
        actor: Any = None,
        person_data: dict[str, Any] | None = None,
        person: Any = None,
        identifiers: list[dict[str, Any]] | None = None,
        contacts: list[dict[str, Any]] | None = None,
        exclude_employee: Any = None,
    ) -> DuplicateReport:
        """Flag possible duplicates before committing to a save. Never blocks.

        Separate from :meth:`create_employee` on purpose: it is advisory, so the create path stays
        free of extra queries and a caller that does not show warnings can skip it. The one signal
        that *does* fail is a repeated identifier value, and that comes from the database constraint
        in ``IdentifierService``, not from here.
        """
        authorize(actor, permissions.ADD)
        if person is not None:
            person_data = person_data or {
                "first_name": person.first_name,
                "last_name": person.last_name,
                "date_of_birth": person.date_of_birth,
            }
        return DuplicateService.check(
            person_data=person_data or {},
            identifiers=identifiers,
            contacts=contacts,
            exclude_employee=exclude_employee,
        )

    @classmethod
    @transactional
    def update_employee(
        cls,
        employee: Employee,
        *,
        actor: Any = None,
        data: dict[str, Any] | None = None,
        person_data: dict[str, Any] | None = None,
        profile_photo: Any = None,
        remove_photo: bool = False,
        ctx: RequestContext = SYSTEM_CONTEXT,
    ) -> Employee:
        """Update the employee row and/or the person behind it.

        ``data`` may only contain ``employee_status`` - everything else belongs to a person field or
        a separate service. ``employee_status`` is routed through :meth:`change_status` so the
        transition rules and the ``archive_employee`` permission still apply.
        """
        authorize(actor, permissions.CHANGE, employee)
        fields = {k: v for k, v in (data or {}).items() if k in ("employee_status",) and v}
        person_changed = bool(person_data) or bool(profile_photo) or remove_photo
        if fields.get("employee_status") and fields["employee_status"] != employee.employee_status:
            employee = cls.change_status(
                employee, actor=actor, status=fields["employee_status"], ctx=ctx
            )
        if person_data or profile_photo or remove_photo:
            person = cls._refresh_person(employee)
            PersonService.update_person(
                person,
                actor=actor,
                data=person_data or {},
                profile_photo=profile_photo,
                remove_photo=remove_photo,
                ctx=ctx,
            )
        if person_changed:
            audit(
                action="employee_updated",
                actor=actor,
                obj_type=EMPLOYEE,
                obj_id=employee.pk,
                after={"personal_details": "updated"},
                ctx=ctx,
            )
            enqueue_outbox_event(
                events.EmployeeUpdated(
                    employee_id=str(employee.pk),
                    employee_code=employee.code,
                    actor_id=_actor_id(actor),
                ),
                aggregate_type=EMPLOYEE,
                aggregate_id=str(employee.pk),
            )
        return employee

    # --------------------------------------------------------------------------------- status
    @classmethod
    @transactional
    def change_status(
        cls,
        employee: Employee,
        *,
        actor: Any,
        status: str,
        reason: str = "",
        ctx: RequestContext = SYSTEM_CONTEXT,
        _restore: bool = False,
    ) -> Employee:
        """Change the master-record status.

        Only ``active``/``inactive`` may be set with ``employees.change_employee``. Moving to or from
        ``archived`` requires ``employees.archive_employee`` and is audited as an archival action
        (ADR-022). There is no delete: see :meth:`assert_can_delete` for why.
        """
        if status not in EmployeeStatus.values:
            raise ValidationException(f"'{status}' is not a valid employee status.")
        if status == employee.employee_status:
            return employee
        archival = EmployeeStatus.ARCHIVED in (status, employee.employee_status)
        if archival:
            authorize(actor, permissions.ARCHIVE, employee)
        else:
            authorize(actor, permissions.CHANGE, employee)
        restoring = _restore and employee.is_archived and status == EmployeeStatus.ACTIVE
        if not restoring and not employee.can_transition_to(status):
            raise BusinessRuleException(
                f"An {employee.get_employee_status_display().lower()} employee cannot become "
                f"{EmployeeStatus(status).label.lower()}.",
                code="invalid_status_transition",
            )
        before = employee.employee_status
        employee.employee_status = status
        employee.archived_at = timezone.now() if status == EmployeeStatus.ARCHIVED else None
        employee.updated_by = actor_or_none(actor)
        employee.save(update_fields=["employee_status", "archived_at", "updated_by", "updated_at"])
        audit(
            action="employee_status_changed",
            actor=actor,
            obj_type=EMPLOYEE,
            obj_id=employee.pk,
            before={"employee_status": before},
            after={"employee_status": status},
            reason=reason,
            ctx=ctx,
        )
        record_event(
            employee=employee,
            event_type="employee_archived"
            if status == EmployeeStatus.ARCHIVED
            else (
                "employee_reactivated"
                if status == EmployeeStatus.ACTIVE
                else "employee_status_changed"
            ),
            summary=f"Status changed to {EmployeeStatus(status).label.lower()}",
            actor=actor,
            payload={"before": before, "employee_status": status},
        )
        event_map: dict[str, Any] = {
            EmployeeStatus.ARCHIVED: events.EmployeeArchived,
            EmployeeStatus.ACTIVE: events.EmployeeReactivated,
        }
        event = event_map.get(status, events.EmployeeStatusChanged)
        enqueue_outbox_event(
            event(
                employee_id=str(employee.pk),
                employee_code=employee.code,
                previous_status=before,
                employee_status=status,
                actor_id=_actor_id(actor),
            ),
            aggregate_type=EMPLOYEE,
            aggregate_id=str(employee.pk),
        )
        return employee

    @classmethod
    @transactional
    def archive(
        cls,
        employee: Employee,
        *,
        actor: Any,
        reason: str = "",
        ctx: RequestContext = SYSTEM_CONTEXT,
    ) -> Employee:
        """Archive an employee. Preferred over deletion - the record stays historically identifiable."""
        return cls.change_status(
            employee, actor=actor, status=EmployeeStatus.ARCHIVED, reason=reason, ctx=ctx
        )

    @classmethod
    @transactional
    def reactivate(
        cls,
        employee: Employee,
        *,
        actor: Any,
        reason: str = "",
        ctx: RequestContext = SYSTEM_CONTEXT,
    ) -> Employee:
        """Return an archived employee to active - the *only* way out of ``archived``.

        Requires ``employees.archive_employee`` (checked in :meth:`change_status`); always audited.
        """
        return cls.change_status(
            employee,
            actor=actor,
            status=EmployeeStatus.ACTIVE,
            reason=reason,
            ctx=ctx,
            _restore=True,
        )

    # --------------------------------------------------------------------------- user link
    @classmethod
    @transactional
    def link_user(
        cls,
        employee: Employee,
        *,
        actor: Any,
        user: Any,
        ctx: RequestContext = SYSTEM_CONTEXT,
    ) -> Employee:
        """Link a login account to an employee (one-to-one). Never creates a user account."""
        return cls._link_user(employee, actor=actor, user=user, ctx=ctx)

    @classmethod
    def _link_user(
        cls, employee: Employee, *, actor: Any, user: Any, ctx: RequestContext
    ) -> Employee:
        authorize(actor, permissions.LINK_USER, employee)
        if user is None:
            raise ValidationException("Choose a user account to link.")
        clash = Employee.objects.filter(user=user).exclude(pk=employee.pk).first()
        if clash is not None:
            # The message reveals only that the account is taken, never by whom.
            raise ConflictException(
                "That user account is already linked to another employee.",
                details={"user": ["Already linked."]},
                code="user_already_linked",
            )
        previous = employee.user
        employee.user = user
        employee.updated_by = actor_or_none(actor)
        employee.save(update_fields=["user", "updated_by", "updated_at"])
        audit(
            action="employee_user_linked",
            actor=actor,
            obj_type=EMPLOYEE,
            obj_id=employee.pk,
            before={"user": str(previous.pk) if previous else ""},
            after={"user": str(user.pk)},
            ctx=ctx,
        )
        record_event(
            employee=employee,
            event_type="user_linked",
            summary="User account linked",
            actor=actor,
            payload={"user_id": str(user.pk)},
        )
        enqueue_outbox_event(
            events.UserLinkedToEmployee(
                employee_id=str(employee.pk),
                employee_code=employee.code,
                user_id=str(user.pk),
                actor_id=_actor_id(actor),
            ),
            aggregate_type=EMPLOYEE,
            aggregate_id=str(employee.pk),
        )
        return employee

    @classmethod
    @transactional
    def unlink_user(
        cls,
        employee: Employee,
        *,
        actor: Any,
        reason: str = "",
        ctx: RequestContext = SYSTEM_CONTEXT,
    ) -> Employee:
        """Remove the link. The user account itself is untouched (ADR-002)."""
        authorize(actor, permissions.LINK_USER, employee)
        previous = employee.user
        if previous is None:
            return employee
        employee.user = None
        employee.updated_by = actor_or_none(actor)
        employee.save(update_fields=["user", "updated_by", "updated_at"])
        audit(
            action="employee_user_unlinked",
            actor=actor,
            obj_type=EMPLOYEE,
            obj_id=employee.pk,
            before={"user": str(previous.pk)},
            after={},
            reason=reason,
            ctx=ctx,
        )
        record_event(
            employee=employee,
            event_type="user_unlinked",
            summary="User account unlinked",
            actor=actor,
        )
        enqueue_outbox_event(
            events.UserUnlinkedFromEmployee(
                employee_id=str(employee.pk),
                employee_code=employee.code,
                user_id=str(previous.pk),
                actor_id=_actor_id(actor),
            ),
            aggregate_type=EMPLOYEE,
            aggregate_id=str(employee.pk),
        )
        return employee

    # --------------------------------------------------------------------------------- delete
    @classmethod
    def assert_can_delete(cls, employee: Employee, *, actor: Any) -> None:
        """Employees are archived, never deleted (ADR-022).

        This method exists so the *reason* is enforced in one place and so the UI/API can explain it,
        rather than each caller deciding for itself. There is deliberately no ``delete_employee``.
        """
        raise BusinessRuleException(
            "Employee records cannot be deleted. Archive the employee instead so their history "
            "stays available.",
            code="employee_deletion_not_allowed",
        )

    # ------------------------------------------------------------------------------- helpers
    @staticmethod
    def _refresh_person(employee: Employee) -> Person:
        """The person, with any stale cached reverse-``employee`` relation dropped.

        ``person.employee`` is cached by Django the first time it is read (and raises if absent), so
        a person fetched before their employee existed would return a stale value afterwards.
        """
        person = employee.person
        person.__dict__.pop("employee", None)
        return person


def _actor_id(actor: Any) -> str | None:
    return str(actor.pk) if getattr(actor, "pk", None) else None
