"""``Employee`` - the person's identity *inside* the organization (docs/adr/ADR-018/019/020).

Intentionally small. ``Employee`` owns exactly four things:

* an immutable, human-readable ``code`` (``EMP-000001``) generated by
  ``apps.common.services.generate_code`` - never the database id, never user-chosen;
* the link to the ``Person`` whose identity it carries (one employee per person);
* the **master-record** status (active / inactive / archived) - *not* the employment lifecycle,
  which belongs to the future ``Employment``/``Lifecycle`` modules;
* an **optional** link to a ``User`` login account (docs/adr/ADR-002).

Deliberately **not** here: position, department, region, area, restaurant, manager, salary,
attendance or leave. Those belong to ``Employment`` / ``Assignment`` / ``Position`` (Phase 4+) and
adding them now would have to be undone later (docs/adr/ADR-020).
"""

from __future__ import annotations

from django.conf import settings
from django.db import models

from apps.common.models import AuditedModel, BusinessCodeModel, UUIDModel

from .base import EmployeeOwnedRecord  # noqa: F401  (re-exported for convenience)


class EmployeeStatus(models.TextChoices):
    """State of the employee *master record* only (ADR-022, docs/architecture/employee-domain.md).

    Not the employment lifecycle: joining, confirmation, transfer, promotion, probation and
    separation are ``Employment`` / ``Lifecycle`` concerns in Phase 4+. Keeping this field narrow is
    what allows those modules to model real lifecycle states later without redefining ``Employee``.
    """

    ACTIVE = "active", "Active"
    INACTIVE = "inactive", "Inactive"
    ARCHIVED = "archived", "Archived"


#: Statuses a normal HR user may set directly. ``archived`` needs ``employees.archive_employee``
#: and is a terminal state (restoring requires an explicit service call).
SELECTABLE_STATUSES = (EmployeeStatus.ACTIVE, EmployeeStatus.INACTIVE)

#: Legal status transitions. ``archived`` is terminal; there is deliberately no "delete".
STATUS_TRANSITIONS: dict[str, frozenset[str]] = {
    EmployeeStatus.ACTIVE: frozenset({EmployeeStatus.INACTIVE, EmployeeStatus.ARCHIVED}),
    EmployeeStatus.INACTIVE: frozenset({EmployeeStatus.ACTIVE, EmployeeStatus.ARCHIVED}),
    EmployeeStatus.ARCHIVED: frozenset(),
}

OPEN_STATUSES = frozenset({EmployeeStatus.ACTIVE, EmployeeStatus.INACTIVE})


class Employee(UUIDModel, BusinessCodeModel, AuditedModel):
    person = models.OneToOneField(
        "employees.Person",
        on_delete=models.PROTECT,
        related_name="employee",
        help_text="The human being. One employee record per person; re-hire creates an Employment.",
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="employee",
        help_text="Optional login account. Never created automatically; linking is audited.",
    )
    employee_status = models.CharField(
        max_length=10,
        choices=EmployeeStatus.choices,
        default=EmployeeStatus.ACTIVE,
        help_text="Master-record state only; employment lifecycle is a later phase.",
    )
    archived_at = models.DateTimeField(
        null=True, blank=True, help_text="Set when the record was archived."
    )

    class Meta:
        db_table = "employees_employee"
        ordering = ["code"]
        indexes = [
            # Covers both "status = x" and the default created-date ordering/filtering.
            models.Index(fields=["employee_status", "created_at"], name="emp_emp_status_idx"),
        ]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(employee_status__in=[s.value for s in EmployeeStatus]),
                name="employees_employee_status_valid",
            ),
            models.CheckConstraint(
                condition=models.Q(employee_status=EmployeeStatus.ARCHIVED)
                | models.Q(archived_at__isnull=True),
                name="employees_employee_archived_flag",
            ),
        ]
        permissions = [
            ("view_sensitive_identity", "Can view sensitive identity data (identifiers, photo)"),
            ("view_identifiers", "Can view employee identifiers"),
            ("view_sensitive_contacts", "Can view personal contact details and addresses"),
            ("view_emergency_contacts", "Can view emergency contacts"),
            ("manage_contacts", "Can add and change employee contacts"),
            ("manage_addresses", "Can add and change employee addresses"),
            ("manage_emergency_contacts", "Can add and change emergency contacts"),
            ("manage_identifiers", "Can add and change employee identifiers"),
            ("manage_relationships", "Can add and change person relationships"),
            ("manage_notes", "Can add and remove internal employee notes"),
            ("link_user", "Can link or unlink a user account to an employee"),
            ("view_employee_timeline", "Can view the employee timeline"),
            ("archive_employee", "Can archive and reactivate employees"),
            ("export_employee", "Can export employee data"),
        ]

    def __str__(self) -> str:
        return f"{self.code} · {self.display_name}"

    # ------------------------------------------------------------------ display helpers
    @property
    def display_name(self) -> str:
        return self.person.display_name if self.person_id else self.code

    @property
    def full_name(self) -> str:
        return self.person.full_name if self.person_id else self.code

    @property
    def is_active(self) -> bool:
        return self.employee_status == EmployeeStatus.ACTIVE

    @property
    def is_archived(self) -> bool:
        return self.employee_status == EmployeeStatus.ARCHIVED

    @property
    def has_user_account(self) -> bool:
        return self.user_id is not None

    def can_transition_to(self, target: str) -> bool:
        return target in STATUS_TRANSITIONS.get(self.employee_status, frozenset())

    # ------------------------------------------------------------- convenience collections
    def primary_contact(self, contact_type: str):
        for contact in self.contacts.all():
            if contact.is_primary and contact.contact_type == contact_type:
                return contact
        return None

    def primary_address(self, address_type: str | None = None):
        from .address import AddressType

        wanted = address_type or AddressType.CURRENT
        for address in self.addresses.all():
            if address.is_primary and address.address_type == wanted:
                return address
        return None

    @property
    def primary_email(self):
        from .contact import ContactType

        return self.primary_contact(ContactType.EMAIL)

    @property
    def primary_mobile(self):
        from .contact import ContactType

        return self.primary_contact(ContactType.MOBILE)

    @property
    def primary_emergency_contact(self):
        for contact in self.emergency_contacts.all():
            if contact.is_primary:
                return contact
        return None
