# Generated by Django 6.1.1 on 2026-10-03 09:32

import apps.common.utils.dates
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=60)),
                ('tax_number', models.CharField(blank=True, max_length=60, verbose_name='tax number (NTN)')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('theme_key', models.SlugField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['code'],
                'permissions': [('change_organization_status', 'Can activate, deactivate, close or archive organization units'), ('move_organization', 'Can move organization units to a different parent'), ('view_organization_history', 'Can view organization history'), ('view_organization_structure', 'Can view the organization overview and tree')],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_company_eff_dates'), models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'inactive', 'archived'])), name='organizations_company_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('structure_type', models.CharField(choices=[('corporate', 'Corporate (locations & departments)'), ('operations', 'Operations (regions, areas & restaurants)')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='organizations.company')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporateLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('city_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a 3-letter upper-case city code, e.g. LHR.')])),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_locations', to='organizations.division')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.UUIDField()),
                ('entity_code', models.CharField(max_length=40)),
                ('event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('renamed', 'Renamed'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('archived', 'Archived'), ('moved', 'Moved (parent changed)'), ('temporarily_closed', 'Temporarily closed'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=24)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'organization history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_type', models.CharField(max_length=32)),
                ('child_id', models.UUIDField()),
                ('parent_type', models.CharField(max_length=32)),
                ('parent_id', models.UUIDField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['child_type', 'child_id', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='organizations.division')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organizations.region')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('temporarily_closed', 'Temporarily closed'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='planned', max_length=20)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('city_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a 3-letter upper-case city code, e.g. LHR.')])),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='organizations.area')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('effective_from', models.DateField(default=apps.common.utils.dates.today_local)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('short_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,8}$', '2-8 upper-case letters/digits, e.g. HR.')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.corporatelocation')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_department_eff_dates'), models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'inactive', 'archived'])), name='organizations_department_status_valid'), models.UniqueConstraint(fields=('location', 'short_code'), name='org_department_location_short'), models.UniqueConstraint(models.F('location'), django.db.models.functions.text.Lower('name'), name='org_department_location_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_division_eff_dates'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'inactive', 'archived'])), name='organizations_division_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='org_division_company_code'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), name='org_division_company_name'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.CheckConstraint(condition=models.Q(('structure_type__in', ['corporate', 'operations'])), name='org_division_structure_valid'),
        ),
        migrations.AddConstraint(
            model_name='corporatelocation',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_corporatelocation_eff_dates'),
        ),
        migrations.AddConstraint(
            model_name='corporatelocation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'inactive', 'archived'])), name='organizations_corporatelocation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='corporatelocation',
            constraint=models.UniqueConstraint(models.F('division'), django.db.models.functions.text.Lower('name'), name='org_location_division_name'),
        ),
        migrations.AddIndex(
            model_name='organizationhistory',
            index=models.Index(fields=['entity_type', 'entity_id', '-timestamp'], name='org_hist_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrelationship',
            index=models.Index(fields=['child_type', 'child_id', 'effective_from'], name='org_rel_child_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrelationship',
            index=models.Index(fields=['parent_type', 'parent_id'], name='org_rel_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='org_rel_dates'),
        ),
        migrations.AddConstraint(
            model_name='organizationrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('child_type', 'child_id'), name='org_rel_one_current_parent'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_region_eff_dates'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'inactive', 'archived'])), name='organizations_region_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(models.F('division'), django.db.models.functions.text.Lower('name'), name='org_region_division_name'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_area_eff_dates'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'inactive', 'archived'])), name='organizations_area_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(models.F('region'), django.db.models.functions.text.Lower('name'), name='org_area_region_name'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city_code'], name='org_restaurant_city_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='organizations_restaurant_eff_dates'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'temporarily_closed', 'closed', 'archived'])), name='organizations_restaurant_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('closing_date__isnull', True), ('opening_date__isnull', True), ('closing_date__gte', models.F('opening_date')), _connector='OR'), name='org_restaurant_dates'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), _connector='OR'), name='org_restaurant_latitude'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), _connector='OR'), name='org_restaurant_longitude'),
        ),
    ]
